// <auto-generated />
namespace TourBookingSolution.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class update06102020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update06102020));
        
        string IMigrationMetadata.Id
        {
            get { return "202006100334247_update-06102020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
